version: '3.9'

networks:
    project:
        name: project
        driver: bridge
        # to control the ips of my network
        ipam:
            driver: default
            config:
                - subnet: 10.0.0.0/24
                  gateway: 10.0.0.1

services:
    service-db:
        networks:
            project:
                ipv4_address: 10.0.0.2
        extends:
            file: service-db/docker-compose.yml
            service: service-db

    service-app:
        networks:
            project:
                ipv4_address: 10.0.0.3
        extends:
            file: service-app/docker-compose.yml
            service: service-app
        depends_on:
            - service-db

    service-frontend:
        networks:
            project:
                ipv4_address: 10.0.0.5
        extends:
            file: service-frontend/docker-compose.yml
            service: service-frontend


volumes:
    db-data: