version: '3.9'

services:
    app:
        image: maven:3.8.7-openjdk-18-slim
        container_name: app
        working_dir: /app
        volumes:
            - .:/app
        command: tail -f /dev/null