version: '3.9'

services:
    app:
        image: maven:3.8.7-openjdk-18-slim
        container_name: app
        working_dir: /app
        volumes:
            - ./app:/app
        command: tail -f /dev/null
    cli:
        image: python:3.8
        container_name: cli
        working_dir: /cli
        volumes:
        - ./cli:/cli
        command: tail -f /dev/null
    gui:
        image: node
        container_name: gui
        working_dir: /gui
        ports:
            - 3000:3000
        volumes:
            - ./gui:/gui
        command: tail -f /dev/null
