version: '3.9'

networks:
    project:
        name: project
        driver: bridge
        # to control the ips of my network
        ipam:
            driver: default
            config:
                - subnet: 10.0.0.0/24
                  gateway: 10.0.0.1

services:
    db:
        image: project-db
        container_name: db
        build: docker/db
        networks:
            project:
                ipv4_address: 10.0.0.2
        volumes:
            - db:/var/lib/postgresql/data/
        ports:
            - "5432:5432"
    app:
        image: project-java
        container_name: app
        build: docker/java
        networks:
            project:
                ipv4_address: 10.0.0.3
        volumes:
            - ./app:/app
        depends_on:
            - db
    gui:
        image: project-gui
        container_name: gui
        build: docker/node
        networks:
            project:
                ipv4_address: 10.0.0.5
        volumes:
            - ./gui:/gui
        depends_on:
            - app


volumes:
    db: